### ISSUE TITLE
Pip can't find iarm

### ISSUE THREAD

**Issue by ARamsey118** [DeepHorizons/iarm#2]
After running ```pip install iarm``` it gives the error 
```Collecting iarm
  Could not find a version that satisfies the requirement iarm (from versions: )
No matching distribution found for iarm```

The setup.py worked, though you may want to mention whether this python 2 or 3

**Comment by DeepHorizons** [comment]
iarm was added as a python package and should now be pip installable.

e92bb79b2f3965e7ead46a0d7d7d7bb463f3230d added a note in the readme saying iarm is a python 3 program.
