### ISSUE TITLE
Missing juypter_client

### ISSUE THREAD

**Issue by ARamsey118** [DeepHorizons/iarm#3]
When trying to run ```python -m iarm_kernel.install``` from the Dockerfile, it throws ```ImportError: No module named juypter_client```. Installing that module from pip fixes the issue

**Comment by DeepHorizons** [comment]
Fixed in 981aa7d0889f2f26564aff8cc56ccb0767caa0b3
The `setup.py` file now explicitly lists the exact packages it needs instead of installing the umbrella `jupyter` package
